import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, '../..');
const LIVE_REPORT_PATH = path.join(REPO_ROOT, '.ops/certifications/live-telegram-process/certification-report.json');
function createSelectedEnvPath(label) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), `ops-live-telegram-process-${label}-`));
  return path.join(dir, 'selected-process-model.env');
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

test('live Telegram process certification auto-loads provider readiness selected model', () => {
  fs.rmSync(path.dirname(LIVE_REPORT_PATH), { force: true, recursive: true });
  const selectedEnvPath = createSelectedEnvPath('handoff');
  fs.mkdirSync(path.dirname(selectedEnvPath), { recursive: true });
  fs.writeFileSync(
    selectedEnvPath,
    [
      '# generated by provider readiness',
      "OPS_LIVE_TELEGRAM_PROCESS_MODEL='openrouter/acme/provider-ready-model'",
      "OPS_PROVIDER_READINESS_MODEL='openrouter/acme/provider-ready-model'",
      ''
    ].join('\n'),
    'utf8'
  );

  const env = { ...process.env };
  delete env.OPS_RUN_LIVE_TELEGRAM_PROCESS_CERT;
  delete env.OPS_LIVE_TELEGRAM_PROCESS_MODEL;
  delete env.OPS_LIVE_TELEGRAM_PROCESS_MODEL_CANDIDATES;
  env.OPS_LIVE_TELEGRAM_PROCESS_SELECTED_MODEL_ENV = selectedEnvPath;

  const result = spawnSync(process.execPath, ['scripts/testing/run-live-telegram-process-certification.mjs'], {
    cwd: REPO_ROOT,
    env,
    encoding: 'utf8'
  });
  assert.equal(result.status, 0, `${result.stderr}\n${result.stdout}`);

  const report = readJson(LIVE_REPORT_PATH);
  assert.equal(report.status, 'skipped');
  assert.equal(report.processModelSelection.candidateSource, 'provider_readiness_selected_env');
  assert.equal(report.processModelSelection.providerReadinessSelectedEnv.used, true);
  assert.equal(report.processModelSelection.providerReadinessSelectedEnv.configured, true);
  assert.equal(report.processModelSelection.providerReadinessSelectedEnv.model, 'openrouter/acme/provider-ready-model');
  assert.equal(report.processModelSelection.candidateCount, 7);
});

test('explicit live Telegram process model overrides provider readiness handoff', () => {
  fs.rmSync(path.dirname(LIVE_REPORT_PATH), { force: true, recursive: true });
  const selectedEnvPath = createSelectedEnvPath('explicit');
  fs.mkdirSync(path.dirname(selectedEnvPath), { recursive: true });
  fs.writeFileSync(
    selectedEnvPath,
    [
      '# generated by provider readiness',
      "OPS_LIVE_TELEGRAM_PROCESS_MODEL='openrouter/acme/provider-ready-model'",
      ''
    ].join('\n'),
    'utf8'
  );

  const env = {
    ...process.env,
    OPS_LIVE_TELEGRAM_PROCESS_MODEL: 'openrouter/acme/explicit-model',
    OPS_LIVE_TELEGRAM_PROCESS_SELECTED_MODEL_ENV: selectedEnvPath
  };
  delete env.OPS_RUN_LIVE_TELEGRAM_PROCESS_CERT;
  delete env.OPS_LIVE_TELEGRAM_PROCESS_MODEL_CANDIDATES;

  const result = spawnSync(process.execPath, ['scripts/testing/run-live-telegram-process-certification.mjs'], {
    cwd: REPO_ROOT,
    env,
    encoding: 'utf8'
  });
  assert.equal(result.status, 0, `${result.stderr}\n${result.stdout}`);

  const report = readJson(LIVE_REPORT_PATH);
  assert.equal(report.status, 'skipped');
  assert.equal(report.processModelSelection.candidateSource, 'explicit_env');
  assert.equal(report.processModelSelection.explicitModelRequested, true);
  assert.equal(report.processModelSelection.providerReadinessSelectedEnv.used, false);
  assert.equal(report.processModelSelection.providerReadinessSelectedEnv.configured, true);
});
